--- #YAML:1.0
name:               PDL-Ngrams
version:            0.03
abstract:           N-Gram utilities for PDL
author:
    - Bryan Jurish <moocow@ling.uni-potsdam.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:                2.4.2
    PDL::VectorValued:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
