--- #YAML:1.0
name:               PDL-Ngrams
version:            0.05.001
abstract:           N-Gram utilities for PDL
author:
    - Bryan Jurish <moocow@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    PDL:                  0
    PDL::VectorValued::Version:  0.07
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:                  0
    PDL::VectorValued::Version:  0.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
